# Generated by Django 6.0.5 on 2026-06-04 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_dailyproductionlog_egg_fields'),
        ('store', '0005_order_inventory_applied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'created_at'], name='store_annou_is_acti_ffb727_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', 'submitted_at'], name='store_conta_is_read_ab28c6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='store_order_user_id_c9744e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='store_order_status_536f03_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='store_order_created_4ba192_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_featured'], name='store_produ_is_avai_7e1b73_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['livestock_species', 'is_available'], name='store_produ_livesto_1972d6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['product', 'is_active'], name='store_promo_product_5b32dd_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='store_promo_start_d_233727_idx'),
        ),
    ]
