services:
  - type: web
    name: tamipee
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: python manage.py migrate && python manage.py create_superuser_from_env
    startCommand: bash start.sh
