# Generated by Django 6.0.5 on 2026-06-04 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Lower


def deduplicate_existing_emails(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    seen_emails = set()

    for user in CustomUser.objects.all().order_by('date_joined', 'id'):
        normalized_email = (user.email or '').strip().lower()

        if not normalized_email:
            if user.email != '':
                user.email = ''
                user.save(update_fields=['email'])
            continue

        if normalized_email in seen_emails:
            user.email = ''
            user.save(update_fields=['email'])
            continue

        seen_emails.add(normalized_email)
        if user.email != normalized_email:
            user.email = normalized_email
            user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(deduplicate_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(Lower('email'), condition=~models.Q(email=''), name='unique_lower_email'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'is_used'], name='accounts_em_user_id_84251d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='accounts_em_expires_858ceb_idx'),
        ),
    ]
