# Generated by Django 6.0.5 on 2026-06-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securityquestion_passwordresetattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usersecurityanswer',
            name='salt',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersecurityanswer',
            name='answer_hash',
            field=models.CharField(max_length=256),
        ),
    ]
