# Generated by Django 6.0.5 on 2026-06-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock/categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Livestock Categories',
            },
        ),
        migrations.CreateModel(
            name='LivestockSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock/species/')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='livestock.livestockcategory')),
            ],
            options={
                'verbose_name_plural': 'Livestock Species',
            },
        ),
        migrations.CreateModel(
            name='LivestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_added', models.PositiveIntegerField(default=0)),
                ('quantity_removed', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, help_text='e.g. Sale, Death, Transfer', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock_records', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='livestock.livestockspecies')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('booster_type', models.CharField(help_text='e.g. Vitamin supplement, Probiotic', max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Daily, Weekly', max_length=100)),
                ('expected_impact', models.TextField(help_text='Describe how this impacts production/growth')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_boosters', to='livestock.livestockspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=150)),
                ('daily_quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feeding_times', models.CharField(help_text='e.g. 7am, 12pm, 5pm', max_length=200)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season', models.CharField(choices=[('all', 'All Seasons'), ('dry', 'Dry Season'), ('rainy', 'Rainy Season')], default='all', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='livestock.livestockspecies')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('production_impact', models.TextField()),
                ('recommended_action', models.TextField()),
                ('expected_yield_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_variations', to='livestock.livestockspecies')),
            ],
        ),
    ]
